# Вопрос 7: 

---

- ## [Расскажите об исключениях в С++.](#title1) 
- ## [В чем их идея?](#title2)
- ## [Как пользоваться оператором throw и конструкцией try...catch?](#title3) 
- ## [В чем разница между исключениями и ошибками времени выполнения?](#title4)

---

### <a id="title1">Расскажите об исключениях в С++.</a>

__ОПР:__ _Исключения_ - это механизм обработки ошибок, который позволяет программисту предусмотреть 
возможность возникновения ошибок во время выполнения программы и определить способ их обработки.

---

### <a id="title2">В чем их идея?</a>

Хотим обрабатывать случаи, когда что-то идет не так (деление на 0, сегфолт и тд)

---

### <a id="title3">Как пользоваться оператором throw и конструкцией try...catch?</a>

__ОПР:__  _Оператор throw_ используется для генерации исключения, а конструкция try...catch - для перехвата и обработки исключения. 
В блоке try помещается код, который может вызвать исключение, а в блоке catch - код, который будет выполняться при возникновении исключения. 
Блоков catch может быть несколько, каждый из которых будет обрабатывать свой тип исключения.

__! Замечание__ _throw_ может как ничего, так и бросать некоторые объект "наверх", тем самым бросаем тот же объект а не новый.

Подробней про catch

- В _catch_ запрещены все приведения типов, кроме приведения типов между наследником и родителем и очевидных (int->const int)
- Если есть несколько _catch_, то компилятор выберет первый подходящий:

```c++
try {
    throw std::out_of_range("aaaa");
} catch (std::exception& ex){
    std::cout << 1;
} catch (std::out_of_range& ex) {
    std::cout << 2;
} catch (...) {
    std::cout << 3;
}
```

Выведется 1.

- _throw_ сделанный в _catch_ игнорируется остальными catch и бросается выше по стеку:

```c++
try {
    throw std::out_of_range("aaaa");
} catch (std::exception& ex){
    throw 1;
    std::cout << 1;
} catch (std::out_of_range& ex) {
    std::cout << 2;
} catch (...) {
    std::cout << 3;
}
```

Такой код упадет с непойманной ошибкой.

---

### <a id="title4">В чем разница между исключениями и ошибками времени выполнения?</a>

Разница между исключениями и ошибками времени выполнения заключается в том, что ошибки __времени выполнения__ - это ошибки, 
которые возникают во время выполнения программы и приводят к ее аварийному завершению. Исключения же предусмотрены программистом и используются для обработки ошибок, 
которые могут возникнуть во время выполнения программы, но не обязательно должны привести к ее аварийному завершению.

___Не любая ошибка является исключением!___

Например, деление на 0 не является исключением.

___try-catch может поймать только то, что было брошено с помощью throw!___

В плюсах есть некоторые ошибки в стандартной библиотеке, которые являются исключениями:

1. dynamic_cast. Бросает он std::bad_cast
2. оператор new. Бросает std::bad_alloc
3. метод at в векторе. Бросает std::out_of_range

---
